version: '3.7'

services:
  test:
    build:
      context: .
      dockerfile: Dockerfile
    command: /bin/ash -c 'npm run dev'
    volumes:
      - .:/test
      - node_modules:/test/node_modules   
    ports:
      - 3000:3000
    depends_on:
      db:
        condition: service_healthy

  db:
    image: 'postgres:14.1'
    volumes: 
      - postgres-db:/var/lib/postgresql/data
      - ./log:/root/log:cached
    restart: always
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      PGDATA: /var/lib/postgresql/data/pgdata
      PSQL_HISTFILE: /root/log/.psql_history
    ports:
      - 5432
    healthcheck:
      test: pg_isready -U test -h 127.0.0.1
      interval: 5s

volumes:
  node_modules:
  postgres-db: